SELECT
SUM(CASE WHEN rating = 'G' THEN 1 ELSE 0 END ) As G,
SUM(CASE WHEN rating = 'R' THEN 1 ELSE 0 END) As R,
SUM(CASE WHEN rating = 'NC-17' THEN 1 ELSE 0 END)AS NC_17,
SUM(CASE WHEN rating = 'PG-13' THEN 1 ELSE 0 END)As PG_13,
SUM(CASE WHEN rating = 'PG'THEN 1 ELSE 0 END)As PG
FROM film